# Generated by Django 4.1.3 on 2022-11-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('date_creation', models.DateField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=25, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='ecole')),
                ('nombre_programmes', models.PositiveSmallIntegerField()),
                ('nom_responsable', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ecole',
            },
        ),
    ]
