# Generated by Django 4.1.3 on 2022-12-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_classroom_course_lesson_level_period_program_and_more'),
        ('school', '0002_ecole_created_at_ecole_created_by_ecole_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('creation_date', models.DateField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=25, null=True)),
                ('address', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='ecole')),
                ('number_program', models.PositiveSmallIntegerField()),
                ('responsible', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'institution',
            },
        ),
        migrations.DeleteModel(
            name='Ecole',
        ),
    ]
