# Generated by Django 4.1.2 on 2022-11-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(max_length=30)),
                ('lien', models.CharField(max_length=50)),
            ],
        ),
    ]
