# Generated by Django 4.1.3 on 2022-11-18 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='est_verifie',
            new_name='is_verified',
        ),
    ]
