# Generated by Django 4.1.3 on 2022-11-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initial_password',
            field=models.CharField(max_length=250, null=True, verbose_name='password2'),
        ),
    ]
