# Generated by Django 4.1.3 on 2022-11-18 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('abbreviation', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'classe',
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('coefficient', models.PositiveSmallIntegerField()),
                ('logo', models.ImageField(blank=True, upload_to='cours')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.classe')),
            ],
            options={
                'db_table': 'cours',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'matiere',
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'niveau',
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('date_debut', models.DateField(max_length=25, null=True)),
                ('date_fin', models.DateField(max_length=25, null=True)),
                ('coefficient', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'periode',
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='programme')),
                ('description', models.TextField(max_length=100)),
                ('nom_responsable', models.CharField(max_length=100)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecole', to='school.ecole')),
            ],
            options={
                'db_table': 'programme',
            },
        ),
        migrations.CreateModel(
            name='Programme_periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.PositiveSmallIntegerField()),
                ('unite_duree', models.CharField(choices=[('mois', 'Mois'), ('annee', 'Annee')], max_length=25, null=True)),
                ('nombre_etudiant', models.IntegerField()),
                ('nombre_professeur', models.IntegerField()),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.periode')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.programme')),
            ],
            options={
                'db_table': 'programme_periode',
            },
        ),
        migrations.CreateModel(
            name='Programme_periode_niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.niveau')),
                ('programme_periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.programme_periode')),
            ],
            options={
                'db_table': 'programme_periode_niveau',
            },
        ),
        migrations.CreateModel(
            name='Matiere_programme_periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Programme_periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.programme_periode')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.matiere')),
            ],
            options={
                'db_table': 'matiere_programme_periode',
            },
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('chapitre', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.classe')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.cours')),
            ],
            options={
                'db_table': 'lecon',
            },
        ),
        migrations.AddField(
            model_name='cours',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.matiere'),
        ),
        migrations.AddField(
            model_name='classe',
            name='Programme_periode_niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.programme_periode_niveau'),
        ),
    ]
